import type { MyStakingItem, StakingItem } from '@/types/dashboard';

export const stakingItems: StakingItem[] = [
  {
    id: '1',
    token: 'ETH',
    tokenIcon: '/tokens/eth.svg',
    name: 'Polygon',
    apy: 18.55,
    status: 'Staked',
    amount: '18.55',
    usdValue: 12.5,
    percentage: 18.5,
    date: '2025-09-12',
  },
  {
    id: '2',
    token: 'USDC',
    tokenIcon: '/tokens/usdc.svg',
    apy: 12.3,
    name: 'Avalanche',
    status: 'Unstaked',
    amount: '5,000',
    usdValue: 500,
    percentage: 18.5,
    date: '2025-09-12',
  },
  {
    id: '3',
    token: 'MATIC',
    tokenIcon: '/tokens/matic.svg',
    name: 'ApeCoin',
    apy: 24.5,
    status: 'Reward',
    amount: '2.0',
    usdValue: 60,
    percentage: 18.5,
    date: '2025-09-12',
  },
];

export const myStakingItems: MyStakingItem[] = [
  {
    id: '1',
    token: 'ETH',
    tokenIcon: '/tokens/eth.svg',
    amount: 5.32,
    percentage: 18.5,
    monthlyEarn: 0.08,
  },
  {
    id: '2',
    token: 'USDC',
    tokenIcon: '/tokens/usdc.svg',
    amount: 1.32,
    percentage: 11.5,
    monthlyEarn: 0.18,
  },
  {
    id: '3',
    token: 'MATIC',
    tokenIcon: '/tokens/matic.svg',
    amount: 2.1,
    percentage: 8.5,
    monthlyEarn: 1.8,
  },
  {
    id: '4',
    token: 'ATOM',
    tokenIcon: '/tokens/atom.svg',
    amount: 9.1,
    percentage: 1.5,
    monthlyEarn: 0.2,
  },
  {
    id: '5',
    token: 'AVAX',
    tokenIcon: '/tokens/avax.svg',
    amount: 1.1,
    percentage: 2.5,
    monthlyEarn: 0.4,
  },
];
